require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe BeadsController do

  # This should return the minimal set of attributes required to create a valid
  # Bead. As you add validations to Bead, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  describe "GET index" do
    it "assigns all beads as @beads" do
      bead = Bead.create! valid_attributes
      get :index
      assigns(:beads).should eq([bead])
    end
  end

  describe "GET show" do
    it "assigns the requested bead as @bead" do
      bead = Bead.create! valid_attributes
      get :show, :id => bead.id
      assigns(:bead).should eq(bead)
    end
  end

  describe "GET new" do
    it "assigns a new bead as @bead" do
      get :new
      assigns(:bead).should be_a_new(Bead)
    end
  end

  describe "GET edit" do
    it "assigns the requested bead as @bead" do
      bead = Bead.create! valid_attributes
      get :edit, :id => bead.id
      assigns(:bead).should eq(bead)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Bead" do
        expect {
          post :create, :bead => valid_attributes
        }.to change(Bead, :count).by(1)
      end

      it "assigns a newly created bead as @bead" do
        post :create, :bead => valid_attributes
        assigns(:bead).should be_a(Bead)
        assigns(:bead).should be_persisted
      end

      it "redirects to the created bead" do
        post :create, :bead => valid_attributes
        response.should redirect_to(Bead.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved bead as @bead" do
        # Trigger the behavior that occurs when invalid params are submitted
        Bead.any_instance.stub(:save).and_return(false)
        post :create, :bead => {}
        assigns(:bead).should be_a_new(Bead)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Bead.any_instance.stub(:save).and_return(false)
        post :create, :bead => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested bead" do
        bead = Bead.create! valid_attributes
        # Assuming there are no other beads in the database, this
        # specifies that the Bead created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Bead.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => bead.id, :bead => {'these' => 'params'}
      end

      it "assigns the requested bead as @bead" do
        bead = Bead.create! valid_attributes
        put :update, :id => bead.id, :bead => valid_attributes
        assigns(:bead).should eq(bead)
      end

      it "redirects to the bead" do
        bead = Bead.create! valid_attributes
        put :update, :id => bead.id, :bead => valid_attributes
        response.should redirect_to(bead)
      end
    end

    describe "with invalid params" do
      it "assigns the bead as @bead" do
        bead = Bead.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Bead.any_instance.stub(:save).and_return(false)
        put :update, :id => bead.id, :bead => {}
        assigns(:bead).should eq(bead)
      end

      it "re-renders the 'edit' template" do
        bead = Bead.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Bead.any_instance.stub(:save).and_return(false)
        put :update, :id => bead.id, :bead => {}
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested bead" do
      bead = Bead.create! valid_attributes
      expect {
        delete :destroy, :id => bead.id
      }.to change(Bead, :count).by(-1)
    end

    it "redirects to the beads list" do
      bead = Bead.create! valid_attributes
      delete :destroy, :id => bead.id
      response.should redirect_to(beads_url)
    end
  end

end
