require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe CrystalsController do

  # This should return the minimal set of attributes required to create a valid
  # Crystal. As you add validations to Crystal, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  describe "GET index" do
    it "assigns all crystals as @crystals" do
      crystal = Crystal.create! valid_attributes
      get :index
      assigns(:crystals).should eq([crystal])
    end
  end

  describe "GET show" do
    it "assigns the requested crystal as @crystal" do
      crystal = Crystal.create! valid_attributes
      get :show, :id => crystal.id
      assigns(:crystal).should eq(crystal)
    end
  end

  describe "GET new" do
    it "assigns a new crystal as @crystal" do
      get :new
      assigns(:crystal).should be_a_new(Crystal)
    end
  end

  describe "GET edit" do
    it "assigns the requested crystal as @crystal" do
      crystal = Crystal.create! valid_attributes
      get :edit, :id => crystal.id
      assigns(:crystal).should eq(crystal)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Crystal" do
        expect {
          post :create, :crystal => valid_attributes
        }.to change(Crystal, :count).by(1)
      end

      it "assigns a newly created crystal as @crystal" do
        post :create, :crystal => valid_attributes
        assigns(:crystal).should be_a(Crystal)
        assigns(:crystal).should be_persisted
      end

      it "redirects to the created crystal" do
        post :create, :crystal => valid_attributes
        response.should redirect_to(Crystal.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved crystal as @crystal" do
        # Trigger the behavior that occurs when invalid params are submitted
        Crystal.any_instance.stub(:save).and_return(false)
        post :create, :crystal => {}
        assigns(:crystal).should be_a_new(Crystal)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Crystal.any_instance.stub(:save).and_return(false)
        post :create, :crystal => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested crystal" do
        crystal = Crystal.create! valid_attributes
        # Assuming there are no other crystals in the database, this
        # specifies that the Crystal created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Crystal.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => crystal.id, :crystal => {'these' => 'params'}
      end

      it "assigns the requested crystal as @crystal" do
        crystal = Crystal.create! valid_attributes
        put :update, :id => crystal.id, :crystal => valid_attributes
        assigns(:crystal).should eq(crystal)
      end

      it "redirects to the crystal" do
        crystal = Crystal.create! valid_attributes
        put :update, :id => crystal.id, :crystal => valid_attributes
        response.should redirect_to(crystal)
      end
    end

    describe "with invalid params" do
      it "assigns the crystal as @crystal" do
        crystal = Crystal.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Crystal.any_instance.stub(:save).and_return(false)
        put :update, :id => crystal.id, :crystal => {}
        assigns(:crystal).should eq(crystal)
      end

      it "re-renders the 'edit' template" do
        crystal = Crystal.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Crystal.any_instance.stub(:save).and_return(false)
        put :update, :id => crystal.id, :crystal => {}
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested crystal" do
      crystal = Crystal.create! valid_attributes
      expect {
        delete :destroy, :id => crystal.id
      }.to change(Crystal, :count).by(-1)
    end

    it "redirects to the crystals list" do
      crystal = Crystal.create! valid_attributes
      delete :destroy, :id => crystal.id
      response.should redirect_to(crystals_url)
    end
  end

end
