require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe EarringTypesController do

  # This should return the minimal set of attributes required to create a valid
  # EarringType. As you add validations to EarringType, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  describe "GET index" do
    it "assigns all earring_types as @earring_types" do
      earring_type = EarringType.create! valid_attributes
      get :index
      assigns(:earring_types).should eq([earring_type])
    end
  end

  describe "GET show" do
    it "assigns the requested earring_type as @earring_type" do
      earring_type = EarringType.create! valid_attributes
      get :show, :id => earring_type.id
      assigns(:earring_type).should eq(earring_type)
    end
  end

  describe "GET new" do
    it "assigns a new earring_type as @earring_type" do
      get :new
      assigns(:earring_type).should be_a_new(EarringType)
    end
  end

  describe "GET edit" do
    it "assigns the requested earring_type as @earring_type" do
      earring_type = EarringType.create! valid_attributes
      get :edit, :id => earring_type.id
      assigns(:earring_type).should eq(earring_type)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new EarringType" do
        expect {
          post :create, :earring_type => valid_attributes
        }.to change(EarringType, :count).by(1)
      end

      it "assigns a newly created earring_type as @earring_type" do
        post :create, :earring_type => valid_attributes
        assigns(:earring_type).should be_a(EarringType)
        assigns(:earring_type).should be_persisted
      end

      it "redirects to the created earring_type" do
        post :create, :earring_type => valid_attributes
        response.should redirect_to(EarringType.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved earring_type as @earring_type" do
        # Trigger the behavior that occurs when invalid params are submitted
        EarringType.any_instance.stub(:save).and_return(false)
        post :create, :earring_type => {}
        assigns(:earring_type).should be_a_new(EarringType)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        EarringType.any_instance.stub(:save).and_return(false)
        post :create, :earring_type => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested earring_type" do
        earring_type = EarringType.create! valid_attributes
        # Assuming there are no other earring_types in the database, this
        # specifies that the EarringType created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        EarringType.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => earring_type.id, :earring_type => {'these' => 'params'}
      end

      it "assigns the requested earring_type as @earring_type" do
        earring_type = EarringType.create! valid_attributes
        put :update, :id => earring_type.id, :earring_type => valid_attributes
        assigns(:earring_type).should eq(earring_type)
      end

      it "redirects to the earring_type" do
        earring_type = EarringType.create! valid_attributes
        put :update, :id => earring_type.id, :earring_type => valid_attributes
        response.should redirect_to(earring_type)
      end
    end

    describe "with invalid params" do
      it "assigns the earring_type as @earring_type" do
        earring_type = EarringType.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        EarringType.any_instance.stub(:save).and_return(false)
        put :update, :id => earring_type.id, :earring_type => {}
        assigns(:earring_type).should eq(earring_type)
      end

      it "re-renders the 'edit' template" do
        earring_type = EarringType.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        EarringType.any_instance.stub(:save).and_return(false)
        put :update, :id => earring_type.id, :earring_type => {}
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested earring_type" do
      earring_type = EarringType.create! valid_attributes
      expect {
        delete :destroy, :id => earring_type.id
      }.to change(EarringType, :count).by(-1)
    end

    it "redirects to the earring_types list" do
      earring_type = EarringType.create! valid_attributes
      delete :destroy, :id => earring_type.id
      response.should redirect_to(earring_types_url)
    end
  end

end
