require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe ModelPlacementsController do

  # This should return the minimal set of attributes required to create a valid
  # ModelPlacement. As you add validations to ModelPlacement, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  describe "GET index" do
    it "assigns all model_placements as @model_placements" do
      model_placement = ModelPlacement.create! valid_attributes
      get :index
      assigns(:model_placements).should eq([model_placement])
    end
  end

  describe "GET show" do
    it "assigns the requested model_placement as @model_placement" do
      model_placement = ModelPlacement.create! valid_attributes
      get :show, :id => model_placement.id
      assigns(:model_placement).should eq(model_placement)
    end
  end

  describe "GET new" do
    it "assigns a new model_placement as @model_placement" do
      get :new
      assigns(:model_placement).should be_a_new(ModelPlacement)
    end
  end

  describe "GET edit" do
    it "assigns the requested model_placement as @model_placement" do
      model_placement = ModelPlacement.create! valid_attributes
      get :edit, :id => model_placement.id
      assigns(:model_placement).should eq(model_placement)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new ModelPlacement" do
        expect {
          post :create, :model_placement => valid_attributes
        }.to change(ModelPlacement, :count).by(1)
      end

      it "assigns a newly created model_placement as @model_placement" do
        post :create, :model_placement => valid_attributes
        assigns(:model_placement).should be_a(ModelPlacement)
        assigns(:model_placement).should be_persisted
      end

      it "redirects to the created model_placement" do
        post :create, :model_placement => valid_attributes
        response.should redirect_to(ModelPlacement.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved model_placement as @model_placement" do
        # Trigger the behavior that occurs when invalid params are submitted
        ModelPlacement.any_instance.stub(:save).and_return(false)
        post :create, :model_placement => {}
        assigns(:model_placement).should be_a_new(ModelPlacement)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        ModelPlacement.any_instance.stub(:save).and_return(false)
        post :create, :model_placement => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested model_placement" do
        model_placement = ModelPlacement.create! valid_attributes
        # Assuming there are no other model_placements in the database, this
        # specifies that the ModelPlacement created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        ModelPlacement.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => model_placement.id, :model_placement => {'these' => 'params'}
      end

      it "assigns the requested model_placement as @model_placement" do
        model_placement = ModelPlacement.create! valid_attributes
        put :update, :id => model_placement.id, :model_placement => valid_attributes
        assigns(:model_placement).should eq(model_placement)
      end

      it "redirects to the model_placement" do
        model_placement = ModelPlacement.create! valid_attributes
        put :update, :id => model_placement.id, :model_placement => valid_attributes
        response.should redirect_to(model_placement)
      end
    end

    describe "with invalid params" do
      it "assigns the model_placement as @model_placement" do
        model_placement = ModelPlacement.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        ModelPlacement.any_instance.stub(:save).and_return(false)
        put :update, :id => model_placement.id, :model_placement => {}
        assigns(:model_placement).should eq(model_placement)
      end

      it "re-renders the 'edit' template" do
        model_placement = ModelPlacement.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        ModelPlacement.any_instance.stub(:save).and_return(false)
        put :update, :id => model_placement.id, :model_placement => {}
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested model_placement" do
      model_placement = ModelPlacement.create! valid_attributes
      expect {
        delete :destroy, :id => model_placement.id
      }.to change(ModelPlacement, :count).by(-1)
    end

    it "redirects to the model_placements list" do
      model_placement = ModelPlacement.create! valid_attributes
      delete :destroy, :id => model_placement.id
      response.should redirect_to(model_placements_url)
    end
  end

end
