require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe RunwayModelsController do

  # This should return the minimal set of attributes required to create a valid
  # RunwayModel. As you add validations to RunwayModel, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  describe "GET index" do
    it "assigns all runway_models as @runway_models" do
      runway_model = RunwayModel.create! valid_attributes
      get :index
      assigns(:runway_models).should eq([runway_model])
    end
  end

  describe "GET show" do
    it "assigns the requested runway_model as @runway_model" do
      runway_model = RunwayModel.create! valid_attributes
      get :show, :id => runway_model.id
      assigns(:runway_model).should eq(runway_model)
    end
  end

  describe "GET new" do
    it "assigns a new runway_model as @runway_model" do
      get :new
      assigns(:runway_model).should be_a_new(RunwayModel)
    end
  end

  describe "GET edit" do
    it "assigns the requested runway_model as @runway_model" do
      runway_model = RunwayModel.create! valid_attributes
      get :edit, :id => runway_model.id
      assigns(:runway_model).should eq(runway_model)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new RunwayModel" do
        expect {
          post :create, :runway_model => valid_attributes
        }.to change(RunwayModel, :count).by(1)
      end

      it "assigns a newly created runway_model as @runway_model" do
        post :create, :runway_model => valid_attributes
        assigns(:runway_model).should be_a(RunwayModel)
        assigns(:runway_model).should be_persisted
      end

      it "redirects to the created runway_model" do
        post :create, :runway_model => valid_attributes
        response.should redirect_to(RunwayModel.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved runway_model as @runway_model" do
        # Trigger the behavior that occurs when invalid params are submitted
        RunwayModel.any_instance.stub(:save).and_return(false)
        post :create, :runway_model => {}
        assigns(:runway_model).should be_a_new(RunwayModel)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        RunwayModel.any_instance.stub(:save).and_return(false)
        post :create, :runway_model => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested runway_model" do
        runway_model = RunwayModel.create! valid_attributes
        # Assuming there are no other runway_models in the database, this
        # specifies that the RunwayModel created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        RunwayModel.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => runway_model.id, :runway_model => {'these' => 'params'}
      end

      it "assigns the requested runway_model as @runway_model" do
        runway_model = RunwayModel.create! valid_attributes
        put :update, :id => runway_model.id, :runway_model => valid_attributes
        assigns(:runway_model).should eq(runway_model)
      end

      it "redirects to the runway_model" do
        runway_model = RunwayModel.create! valid_attributes
        put :update, :id => runway_model.id, :runway_model => valid_attributes
        response.should redirect_to(runway_model)
      end
    end

    describe "with invalid params" do
      it "assigns the runway_model as @runway_model" do
        runway_model = RunwayModel.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        RunwayModel.any_instance.stub(:save).and_return(false)
        put :update, :id => runway_model.id, :runway_model => {}
        assigns(:runway_model).should eq(runway_model)
      end

      it "re-renders the 'edit' template" do
        runway_model = RunwayModel.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        RunwayModel.any_instance.stub(:save).and_return(false)
        put :update, :id => runway_model.id, :runway_model => {}
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested runway_model" do
      runway_model = RunwayModel.create! valid_attributes
      expect {
        delete :destroy, :id => runway_model.id
      }.to change(RunwayModel, :count).by(-1)
    end

    it "redirects to the runway_models list" do
      runway_model = RunwayModel.create! valid_attributes
      delete :destroy, :id => runway_model.id
      response.should redirect_to(runway_models_url)
    end
  end

end
