require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe ShowcasePlacementsController do

  # This should return the minimal set of attributes required to create a valid
  # ShowcasePlacement. As you add validations to ShowcasePlacement, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  describe "GET index" do
    it "assigns all showcase_placements as @showcase_placements" do
      showcase_placement = ShowcasePlacement.create! valid_attributes
      get :index
      assigns(:showcase_placements).should eq([showcase_placement])
    end
  end

  describe "GET show" do
    it "assigns the requested showcase_placement as @showcase_placement" do
      showcase_placement = ShowcasePlacement.create! valid_attributes
      get :show, :id => showcase_placement.id
      assigns(:showcase_placement).should eq(showcase_placement)
    end
  end

  describe "GET new" do
    it "assigns a new showcase_placement as @showcase_placement" do
      get :new
      assigns(:showcase_placement).should be_a_new(ShowcasePlacement)
    end
  end

  describe "GET edit" do
    it "assigns the requested showcase_placement as @showcase_placement" do
      showcase_placement = ShowcasePlacement.create! valid_attributes
      get :edit, :id => showcase_placement.id
      assigns(:showcase_placement).should eq(showcase_placement)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new ShowcasePlacement" do
        expect {
          post :create, :showcase_placement => valid_attributes
        }.to change(ShowcasePlacement, :count).by(1)
      end

      it "assigns a newly created showcase_placement as @showcase_placement" do
        post :create, :showcase_placement => valid_attributes
        assigns(:showcase_placement).should be_a(ShowcasePlacement)
        assigns(:showcase_placement).should be_persisted
      end

      it "redirects to the created showcase_placement" do
        post :create, :showcase_placement => valid_attributes
        response.should redirect_to(ShowcasePlacement.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved showcase_placement as @showcase_placement" do
        # Trigger the behavior that occurs when invalid params are submitted
        ShowcasePlacement.any_instance.stub(:save).and_return(false)
        post :create, :showcase_placement => {}
        assigns(:showcase_placement).should be_a_new(ShowcasePlacement)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        ShowcasePlacement.any_instance.stub(:save).and_return(false)
        post :create, :showcase_placement => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested showcase_placement" do
        showcase_placement = ShowcasePlacement.create! valid_attributes
        # Assuming there are no other showcase_placements in the database, this
        # specifies that the ShowcasePlacement created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        ShowcasePlacement.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => showcase_placement.id, :showcase_placement => {'these' => 'params'}
      end

      it "assigns the requested showcase_placement as @showcase_placement" do
        showcase_placement = ShowcasePlacement.create! valid_attributes
        put :update, :id => showcase_placement.id, :showcase_placement => valid_attributes
        assigns(:showcase_placement).should eq(showcase_placement)
      end

      it "redirects to the showcase_placement" do
        showcase_placement = ShowcasePlacement.create! valid_attributes
        put :update, :id => showcase_placement.id, :showcase_placement => valid_attributes
        response.should redirect_to(showcase_placement)
      end
    end

    describe "with invalid params" do
      it "assigns the showcase_placement as @showcase_placement" do
        showcase_placement = ShowcasePlacement.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        ShowcasePlacement.any_instance.stub(:save).and_return(false)
        put :update, :id => showcase_placement.id, :showcase_placement => {}
        assigns(:showcase_placement).should eq(showcase_placement)
      end

      it "re-renders the 'edit' template" do
        showcase_placement = ShowcasePlacement.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        ShowcasePlacement.any_instance.stub(:save).and_return(false)
        put :update, :id => showcase_placement.id, :showcase_placement => {}
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested showcase_placement" do
      showcase_placement = ShowcasePlacement.create! valid_attributes
      expect {
        delete :destroy, :id => showcase_placement.id
      }.to change(ShowcasePlacement, :count).by(-1)
    end

    it "redirects to the showcase_placements list" do
      showcase_placement = ShowcasePlacement.create! valid_attributes
      delete :destroy, :id => showcase_placement.id
      response.should redirect_to(showcase_placements_url)
    end
  end

end
