require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe StonesController do

  # This should return the minimal set of attributes required to create a valid
  # Stone. As you add validations to Stone, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  describe "GET index" do
    it "assigns all stones as @stones" do
      stone = Stone.create! valid_attributes
      get :index
      assigns(:stones).should eq([stone])
    end
  end

  describe "GET show" do
    it "assigns the requested stone as @stone" do
      stone = Stone.create! valid_attributes
      get :show, :id => stone.id
      assigns(:stone).should eq(stone)
    end
  end

  describe "GET new" do
    it "assigns a new stone as @stone" do
      get :new
      assigns(:stone).should be_a_new(Stone)
    end
  end

  describe "GET edit" do
    it "assigns the requested stone as @stone" do
      stone = Stone.create! valid_attributes
      get :edit, :id => stone.id
      assigns(:stone).should eq(stone)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Stone" do
        expect {
          post :create, :stone => valid_attributes
        }.to change(Stone, :count).by(1)
      end

      it "assigns a newly created stone as @stone" do
        post :create, :stone => valid_attributes
        assigns(:stone).should be_a(Stone)
        assigns(:stone).should be_persisted
      end

      it "redirects to the created stone" do
        post :create, :stone => valid_attributes
        response.should redirect_to(Stone.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved stone as @stone" do
        # Trigger the behavior that occurs when invalid params are submitted
        Stone.any_instance.stub(:save).and_return(false)
        post :create, :stone => {}
        assigns(:stone).should be_a_new(Stone)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Stone.any_instance.stub(:save).and_return(false)
        post :create, :stone => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested stone" do
        stone = Stone.create! valid_attributes
        # Assuming there are no other stones in the database, this
        # specifies that the Stone created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Stone.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => stone.id, :stone => {'these' => 'params'}
      end

      it "assigns the requested stone as @stone" do
        stone = Stone.create! valid_attributes
        put :update, :id => stone.id, :stone => valid_attributes
        assigns(:stone).should eq(stone)
      end

      it "redirects to the stone" do
        stone = Stone.create! valid_attributes
        put :update, :id => stone.id, :stone => valid_attributes
        response.should redirect_to(stone)
      end
    end

    describe "with invalid params" do
      it "assigns the stone as @stone" do
        stone = Stone.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Stone.any_instance.stub(:save).and_return(false)
        put :update, :id => stone.id, :stone => {}
        assigns(:stone).should eq(stone)
      end

      it "re-renders the 'edit' template" do
        stone = Stone.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Stone.any_instance.stub(:save).and_return(false)
        put :update, :id => stone.id, :stone => {}
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested stone" do
      stone = Stone.create! valid_attributes
      expect {
        delete :destroy, :id => stone.id
      }.to change(Stone, :count).by(-1)
    end

    it "redirects to the stones list" do
      stone = Stone.create! valid_attributes
      delete :destroy, :id => stone.id
      response.should redirect_to(stones_url)
    end
  end

end
